@ECHO OFF
ECHO Please wait while lottery system is initializing...
start "chrome" http://localhost:3000
call yarn start
echo Lottery system has been initialized successfully...
echo Opening in Browser....

PAUSE